### PR TITLE
feature: added IsPresent support

### PR DESCRIPTION
**Pull request by Vorstenbosch**
adding IsPresent support according to https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html

### CODE REVIEW

**Comment by Vorstenbosch** [comment]
Hello, 

Ah yes, it has the same behaviour although inverted. I could reuse it but not sure what is the cleanest approach. Would this work for you?

```'use strict'
import {IsUndefined} from './is-undefined'

module.exports = function isPresentOperator (inputValue, comparisonValue, candidateStateName, cache) {
  return IsUndefined(inputValue, !comparisonValue, candidateStateName, cache)
}
```

**Comment by meenahoda** [comment]
Hi @Vorstenbosch 

Yeah, that looks good to me - avoids the duplication :)

Thank you!

**Comment by Vorstenbosch** [comment]
I updated the PR, please take another look.

**Comment by meenahoda** [comment]
@Vorstenbosch  looks good to me, thank you.

**Review by meenahoda — APPROVED** [review]

**Pull request merged**
